### ISSUE TITLE
Vagrant, trusty64 and java 8 for the latest nextflow

### ISSUE THREAD

**Issue by darked89** [mfoll/robust-regression-caller#188]
Hello,

while executing
```
vagrant up
```
I got:
```
<snip>
default: Downloading nextflow dependencies. It may require a few seconds, please wait .. 
    default: ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
```

changing 
```
config.vm.box = "ubuntu/trusty64"
# to i.e.
config.vm.box = "ubuntu/xenial64"
```
fixes Nextflow install in the Vagrant box

DK

**Comment by mfoll** [comment]
Thanks, we have not been using vagrant for some time, and it clearly needed an update!  
<img width="997" alt="image" src="https://user-images.githubusercontent.com/3366818/84471523-cc833480-ac85-11ea-8d39-e6f3400ce735.png">

We will include the change in the next release.
