### ISSUE TITLE
 Failed to open file 

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [mfoll/robust-regression-caller#191]
Hi, getting this error.. not sure why.

Thanks,

needlestack.sh --ref=79900cent.fa --bam_folder=bam/ --output_vcf=needle.vcf --use_file_name

--------------------------------------------------------
NEEDLESTACK v1.1: A MULTI-SAMPLE SOMATIC VARIANT CALLER
--------------------------------------------------------
Copyright (C) 2017 IARC/WHO
This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE.txt
This is free software, and you are welcome to redistribute it
under certain conditions; see LICENSE.txt for details.
--------------------------------------------------------
Mandatory arguments:
Reference in fasta format (--ref)                               : 79900cent.fa
Input BAM folder (--bam_folder)                                 : bam/
output vcf (--output_vcf)                                       : needle.vcf
Options:
output folder (--output_folder)                                 :
Intervals for calling (--region)                                :
Perform a tumor-normal somatic variant calling (--tn_pairs)     : no
To consider a site for calling:
     minimum median coverage (--min_dp)                         : 30
     minimum of alternative reads (--min_ao)                    : 3
Phred-scale qvalue threshold (--min_qval)                       : 50
Strand bias measure (--sb_type)                                 : SOR
Strand bias threshold for SNVs (--sb_snv)                       : 100
Strand bias threshold for indels (--sb_indel)                   : 100
Minimum allelic fraction for power computations (--power_min_af): -1
Sigma parameter for germline (--sigma)                          : 0.1
Samtools minimum mapping quality (--map_qual)                   : 0
Samtools minimum base quality (--base_qual)                     : 13
Samtools maximum coverage before downsampling (--max_dp)        : 50000
Sample names definition (--use_file_name)                       : FILE
PDF regression plots (--plots)                                  : ALL
Flags:
Alignment plots (--do_alignments)                               : no
Labeling outliers in regression plots (--no_labels)             : yes
Add contours in plots and plot min(AF)~DP (--no_contours)       : yes
Output all SNVs (--all_SNVs)                                    : no
Perform an extra-robust regression (--extra_robust_gl)          : no
Skip indels (--no_indels)                                       : no

WARNING : minimum allelic fraction for power computations must be in [0,1] (--power_min_af)
[warning] samtools mpileup option `L` is functional, but deprecated. Please switch to using bcftools mpileup in future.
[E::hts_open_format] Failed to open file A00119:345:HY7KVDRXX:1:2119:2347:35243:0-150
[mpileup] failed to open A00119:345:HY7KVDRXX:1:2119:2347:35243:0-150: Protocol not supported
[1] "2021-06-07 16:16:38 AEST"
[1] 0.2
[1] "2021-06-07 16:16:40 AEST"
mv: cannot stat '*.pdf': No such file or directory

**Comment by mfoll** [comment]
Hi,

I suspect there is an issue with the file names when I see this:
`[mpileup] failed to open A00119:345:HY7KVDRXX:1:2119:2347:35243:0-150: Protocol not supported`
Maybe check with a toy example renaming your files to see if this is the issue?

**Comment by theo-allnutt-bioinformatics** [comment]
File names are ok. That's a read name, not a file, which is what I don't understand. Thanks.

**Comment by mfoll** [comment]
Oh right, then I guess this is a samtools related issue. Maybe try to manually run the command on a few BAM files to isolate the issue, it is here in the code:
`samtools mpileup --fasta-ref $fasta_ref --region $region --ignore-RG --min-BQ $base_qual --min-MQ $map_qual --max-idepth 1000000 --max-depth $max_dp $bam_folder*.bam`
https://github.com/IARCbioinfo/needlestack/blob/master/bin/needlestack.sh#L477
