### ISSUE TITLE
Is 'QUAL' in vcf file the 'QVAL' in the paper?

### ISSUE THREAD

**Issue by isshamie** [mfoll/robust-regression-caller#193]
Hello, I'm trying to understand what QUAL is- the max value I see is 1000. In the paper I see 'QVAL', and the max is 100. 

Thanks!

**Comment by mfoll** [comment]
Hi, yes, the phred-scaled q-value (noted QVAL in the paper) is what we report in the VCF as "QUAL" (QUAL is the name imposed in the VCF specification).
